### ISSUE TITLE
Possible bug in valid language tag rules

### ISSUE THREAD

**Issue by annethyme** [qualweb/act-rules#1]
I think I have found a bug in the Qualweb implementation of the ACT Rule "Element with lang attribute has valid language tag" (https://act-rules.github.io/rules/de46e4).

It seems that the Qualweb implementation differentiates between tags based on capitalisation, which it shouldn’t according to [BCP 47 “Tags for Identifying Languages](https://tools.ietf.org/html/bcp47): 

> “2.1.1.  Formatting of Language Tags
> At all times, language tags and their subtags, including private use and extensions, are to be treated as case insensitive: there exist conventions for the capitalisation of some of the subtags, but these MUST NOT be taken to carry meaning.”

In this Qualweb result, http://qualweb.di.fc.ul.pt/evaluator/http%253A%252F%252Fuvm.dk, lang="DA" is flagged even though it is a valid language tag for Danish language: 

`<div id="coiConsentBanner" role="banner" aria-describedby="coiBannerHeadline" aria-labelledby="cookie_summary" class="coi-consent-banner BannerBottom BannerLeft" lang="DA" dir="ltr" aria-hidden="false" style="display: block;"></div>`

I expect the implementation of the rule "HTML page lang attribute has valid language tag" (https://act-rules.github.io/rules/bf051a) has the same issue.

I have also created an issue in the ACT Rules repository for creating test cases with different capitalisation for the valid language tag rules: https://github.com/act-rules/act-rules.github.io/issues/1499

**Comment by carlosapaduarte** [comment]
Hey @annethyme 
Thanks for spotting this. It's been fixed, so if you update to the last version it should work fine.

**Comment by annethyme** [comment]
Hi @carlosapaduarte,

This sounds really good. Thanks for the swift action on this.
We are keeping our setup steady for the current batch of evaluations we are doing, but we are looking forward to updating in preparation for the next batch.

**Comment by annethyme** [comment]
@carlosapaduarte, should this bug be fixed in the Qualweb version that is running on http://qualweb.di.fc.ul.pt/ ?
I just ran a test on a web page there and got the result that lang="DA" is an invalid language attribute for the rule "ELEMENT WITHIN BODY HAS VALID LANG ATTRIBUTE" (ACT-R22). So it looks like the bug persists in at least one place.

**Comment by carlosapaduarte** [comment]
@annethyme sorry about that. We've updated everything (including the website) with the fix. It should be okay now.

**Comment by annethyme** [comment]
@carlosapaduarte, thanks for the as always swift action :)
