### ISSUE TITLE
`dialog` and `alertdialog` missing from valid role values

### ISSUE THREAD

**Issue by iamfrank** [qualweb/act-rules#2]
https://github.com/qualweb/act-rules/blob/64702b1128668d0e1e88c54e9414a4af92b7dd6e/src/rules/QW-ACT-R20.ts#L27

Hi there

I'm getting consistent fails in Qualweb reports because my web page has an element with `role="alertdialog"`.
I see that `dialog` and `alertdialog` are not in your list of valid `role` values, even though they are standard WAI-ARIA roles (See https://www.w3.org/TR/wai-aria-1.1/#alertdialog ). 
Is there a particular reason for that?

Best regards,

**Comment by carlosapaduarte** [comment]
Hi Frank

Thanks for reporting this. That list is outdated, and we missed it when replacing the valid roles list with a resource shared among rules. We will fix this in an upcoming release of QualWeb and update this issue with that information.
